# Generated by Django 6.0.2 on 2026-02-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100, verbose_name='Kalkış Şehri')),
                ('destination', models.CharField(max_length=100, verbose_name='Varış Şehri')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('duration', models.CharField(blank=True, help_text='Örn: 10-12 saat', max_length=100, verbose_name='Tahmini Süre')),
                ('frequency', models.CharField(default='Günlük sefer', max_length=100, verbose_name='Sefer Sıklığı')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Güzergah',
                'verbose_name_plural': 'Güzergahlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('icon', models.CharField(choices=[('truck', 'Kamyon'), ('arrow', 'Ok'), ('building', 'Bina'), ('package', 'Paket')], default='truck', max_length=50, verbose_name='İkon')),
                ('features', models.TextField(blank=True, default='', help_text='Her satıra bir özellik yazın', verbose_name='Özellikler')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['order'],
            },
        ),
    ]
