# Generated by Django 6.0.2 on 2026-02-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambarapp', '0003_add_slug_image_detail_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['pk'], 'verbose_name': 'Hizmet', 'verbose_name_plural': 'Hizmetler'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='features',
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.AlterField(
            model_name='route',
            name='slug',
            field=models.SlugField(blank=True, help_text='Boş bırakın, otomatik oluşturulur', max_length=220, null=True, unique=True, verbose_name='URL (Slug)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text="Kartlarda ve meta description'da kullanılır (1-2 cümle)", verbose_name='Kısa Açıklama'),
        ),
        migrations.AlterField(
            model_name='service',
            name='detail_content',
            field=models.TextField(blank=True, help_text='Detay sayfasında gösterilecek SEO içeriği. Paragraflar arası boş satır bırakın.', verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Önerilen boyut: 1200×800 px', null=True, upload_to='services/', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='Boş bırakın, otomatik oluşturulur', max_length=220, null=True, unique=True, verbose_name='URL (Slug)'),
        ),
    ]
